# /conchayoro/frontend/Dockerfile

# Use a imagem base do NGINX com Alpine
FROM nginx:alpine

# Copie o conteúdo do diretório do frontend para o diretório padrão do NGINX
COPY . /usr/share/nginx/html

# Exponha a porta 3000
EXPOSE 3000
